### PR TITLE
Feature playerpage

### PR DESCRIPTION
**Pull request by emmanuellekamwa**
In this project, I and my partner gained more insight and understanding working with media. We successfully embedded a youtube video and thumbnail images from the YouTube player page.

In replicating the page, we were able to boost our HTML and CSS3 skills following the Odin Project page: https://www.theodinproject.com/courses/html5-and-css3/lessons/embedding-images-and-video.

Project Milestones:
We were able to reach all the set milestones, some of which were:

The site must have an embedded image representing the logo
Input tag for a search bar
Three embedded images representing icons located on the rightmost part of the nabber.
The embedded video displaying with title, number of views, likes and dislikes as well as a share button
The site should also show recommended video’s thumbnail preview as an image with title and number of views
After the work was done, we used the recommended site: here to validate our HTML and corrected all the bugs found.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @emmanuellekamwa and @acushlakoncept 
### You have done good so far :clap: However, you have a few issues to solve
- Write a more detailed readme file [check this example](https://github.com/microverseinc/readme-template)
- Remove the commented code in your html and css files
commented out code
- Also, add a more descriptive pull request mentioning what you were able to do in this project [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
### Make these changes and resubmit for another code review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### You are doing really well, there still issues you need to address. You are almost done.
- Do not push unrequired files to the repo, instead add a .gitignore files and add them there example this file .DS_Store
- Also, you have not added a descriptive pull request from the previous review.

### Make the changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by acushlakoncept** [comment]
In this project, I and my partner gained more insight and understanding working with media. We successfully embedded a youtube video and thumbnail images from the YouTube player page.

In replicating the page, we were able to boost our HTML and CSS3 skills following the Odin Project page: https://www.theodinproject.com/courses/html5-and-css3/lessons/embedding-images-and-video.

**Project Milestones:**
We were able to reach all the set milestones, some of which were:
- The site must have an embedded image representing the logo
- Input tag for a search bar
- Three embedded images representing icons located on the rightmost part of the nabber.
- The embedded video displaying with title, number of views, likes and dislikes as well as a share button
- The site should also show recommended video’s thumbnail preview as an image with title and number of views

After the work was done, we used the recommended site: here to validate our HTML and corrected all the bugs found.

**Comment by lekegitrepo** [comment]
#### Hi @emmanuellekamwa and @acushlakoncept :+1: :100:
#### Good job for implementing the required changes. This project is approved.

#### Note: You should put the description of the pull request at the top by clicking the three dots on the textarea with "No description provided." text and click edit.

### Reviewed by Temitayo Adeleke

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Comment by acushlakoncept** [comment]
> #### Hi @emmanuellekamwa and @acushlakoncept 👍 💯
> #### Good job for implementing the required changes. This project is approved.
> #### Note: You should put the description of the pull request at the top by clicking the three dots on the textarea with "No description provided." text and click edit.
> ### Reviewed by Temitayo Adeleke
> * Github: [@lekegitrepo](https://github.com/lekegitrepo)
> * Twitter: [@leketemi](https://twitter.com/leketemi)
> * Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Pull request merged**
